checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: true

enableImmutableInstalls: false

enableInlineHunks: true

enableMessageNames: false

networkConcurrency: 100

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs
